FROM debian:stretch-slim

ARG RSPAMD_HOME=/var/lib/rspamd
ARG RSPAMD_LOG=/var/log/rspamd
ARG RSPAMD_USER=_rspamd
ARG DEBIAN_FRONTEND=noninteractive
ENV LC_ALL C

RUN apt-get update && apt-get install -y \
	automake \
	autotools-dev \
	build-essential \
	ca-certificates \
	cmake \
	git \
	libevent-dev \
	libfann-dev \
	libglib2.0-dev \
	libicu-dev \
	liblua5.1-dev \
	libmagic-dev \
	libsqlite3-dev \
	libssl-dev \
	lua5.1 \
	make \
	openssl \
	ragel \
	sqlite3 \
	&& rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/vstakhov/rspamd.git \
	&& mkdir rspamd.build && cd rspamd.build \
	&& cmake ../rspamd \
	&& make \
	&& make install \
	&& make clean \
	&& cd .. && rm -rf rspamd rspamd.build

RUN adduser --quiet \
	--system \
	--group \
	--home ${RSPAMD_HOME} \
	--no-create-home \
	--disabled-login \
	--gecos "rspamd spam filtering system" \
	--force-badname \
	${RSPAMD_USER} \
	&& mkdir -p ${RSPAMD_HOME} ${RSPAMD_LOG} \
	&& chown ${RSPAMD_USER}: ${RSPAMD_HOME} ${RSPAMD_LOG}

COPY settings.conf /etc/rspamd/modules.d/settings.conf
#COPY ratelimit.lua /usr/share/rspamd/lua/ratelimit.lua
#COPY lua_util.lua /usr/share/rspamd/lib/lua_util.lua
COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY tini-arm64 /sbin/tini
RUN chmod +x /sbin/tini

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/usr/local/bin/rspamd", "-f", "-u", "_rspamd", "-g", "_rspamd"]
